parameters:
  - name: CreateArtifacts
    type: boolean
    default: true

jobs:

- job: BuildArtifacts
  displayName: Build Artifacts

  variables:
    - template: /eng/ci/templates/variables/build.yml@self
    - name: packages_path
      value: $(Build.ArtifactStagingDirectory)/packages

  templateContext:
    outputParentDirectory: $(packages_path)
    outputs:
    - ${{ if eq(parameters.CreateArtifacts, true) }}:
      - output: pipelineArtifact
        displayName: Publish artifacts
        path: $(packages_path)
        artifact: drop

  steps:

  - task: UseDotNet@2 # The pinned SDK we use to build
    displayName: Install .NET SDK from global.json
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: Build project
    inputs:
      command: custom
      custom: build
      arguments: -c $(configuration)
      projects: $(project)

  - task: PowerShell@2
    displayName: 'Setup E2E tests'
    inputs:
      targetType: filePath
      filePath: $(Build.SourcesDirectory)/eng/ci/templates/scripts/setup-e2e-tests.ps1
      arguments: '-RepoRoot $(RepoRoot)'
      pwsh: true

  - task: DotNetCoreCLI@2
    displayName: Run tests
    inputs:
      command: test
      arguments: --no-build -c $(configuration)
      projects: $(project)

  - ${{ if eq(parameters.CreateArtifacts, true) }}:
    - template: ci/sign-files.yml@eng
      parameters:
        displayName: Sign assemblies
        folderPath: out/bin/Worker.Extensions.Mcp/
        pattern: Microsoft.Azure.Functions.Worker.Extensions.Mcp.dll
        signType: dll

    - task: DeleteFiles@1
      displayName: Delete CodeSignSummary files
      inputs:
        sourceFolder: out/bin/Worker.Extensions.Mcp/
        contents: '**/CodeSignSummary-*.md'

    - template: ci/sign-files.yml@eng
      parameters:
        displayName: Sign extension assemblies
        folderPath: out/bin/Extensions.Mcp/
        pattern: Microsoft.Azure.Functions.Extensions.Mcp.dll
        signType: dll

    - task: DeleteFiles@1
      displayName: Delete CodeSignSummary files
      inputs:
        sourceFolder: out/bin/Extensions.Mcp/
        contents: '**/CodeSignSummary-*.md'

    - task: DotNetCoreCLI@2
      displayName: 'Build package'
      inputs:
        command: custom
        custom: pack
        arguments: --no-build -c Release -o $(packages_path)
        projects: $(project)

    - template: ci/sign-files.yml@eng
      parameters:
        displayName: Sign nuget packages
        folderPath: $(packages_path)
        pattern: '*.nupkg'
        signType: nuget

    - task: DeleteFiles@1
      displayName: Delete CodeSignSummary files
      inputs:
        sourceFolder: $(packages_path)
        contents: '**/CodeSignSummary-*.md'
